version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      all-actions:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/poetry-project"
    schedule:
      interval: "monthly"
    groups:
      patch:
        update-types:
          - "patch"

  - package-ecosystem: "npm"
    directory: "/functions"
    schedule:
      interval: "monthly"
    groups:
      patch:
        update-types:
          - "patch"
