name: build cloud funcstions

on: pull_request

defaults:
  run:
    working-directory: functions

jobs:
  job_id:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 14
    - id: 'build'
      run: |
        npm install
        npm run build

    - id: 'commit'
      uses: stefanzweifel/git-auto-commit-action@v4.12.0
      with:
        commit_message: update functions
        commit_user_name: GitHub Actions
        commit_user_email: actions@github.com
