name: deploy cloud funcstions

on:
  push:
    branches: [ master ]

defaults:
  run:
    working-directory: functions

jobs:
  job_id:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
    - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
      with:
        node-version: 16

    - id: 'build'
      run: |
        npm ci
        npm run build

    - id: 'auth'
      uses: 'google-github-actions/auth@09cecabe1f169596b81c2ef22b40faff87acc460' # v0.9.0
      with:
        workload_identity_provider: 'projects/38660830011/locations/global/workloadIdentityPools/demo/providers/demo'
        service_account: 'deploy@cloud-functions-playgrou-aa0f6.iam.gserviceaccount.com'

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloud-functions@324936294863e3c89a0432dd625cffc06c09a7b1' # v.11.0
      with:
        name: 'helloWorld'
        source_dir: 'functions'
        region: 'asia-northeast1'
        runtime: 'nodejs16'
