name: deploy cloud funcstions

on:
  push:
    branches: [ master ]

defaults:
  run:
    working-directory: functions

jobs:
  job_id:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
      with:
        node-version: 16

    - id: 'build'
      run: |
        npm ci
        npm run build

    - id: 'auth'
      uses: 'google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093' # v3.0.0
      with:
        workload_identity_provider: 'projects/38660830011/locations/global/workloadIdentityPools/demo/providers/demo'
        service_account: 'deploy@cloud-functions-playgrou-aa0f6.iam.gserviceaccount.com'

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloud-functions@ab10d6b9be21630aafc15ced4c464c16cd6640d6' # v.11.4.0.0
      with:
        name: 'helloWorld'
        source_dir: 'functions'
        region: 'asia-northeast1'
        runtime: 'nodejs16'
